return  
	{
		"internal_Reloading",
		"internal_ReloadStart",
		"internal_Cycled",
		"internal_CycleStart",
		"internal_Chambered",
		"internal_BulletsFired",
		"internal_MuzzleMax",
		"internal_MuzzleCycle",
		"internal_TgtAngle",
		"internal_CurAngle",
		"internal_Zero",
		"internal_IndirectFire",
		"internal_Range",
		"internal_AimDist",
		"internal_VehAngle",
		"internal_Infrared",
		"internal_NightVis",
		"internal_Firemode",
		
		"internal_holdingLMB",
	}
